### ISSUE TITLE
Validators are called multiple times for the same message

### ISSUE THREAD

**Issue by iulianpascalau** [libp2p/go-libp2p-pubsub#173]
Hello

There seem to be an issue in which validators are called multiple times for the same message (same peer, same seqno). After placing some trace print lines in pubsub.go here is what I have found out:
suppose we have a message m with an id (id = peerID+seqNo)
1. first time message m enters the pushmsg func, it queries seenMessage func which will return false so it can continue. It launches the validator and exits through the return on line 648;
2. it might happen that the same message comes again, enters the same pushmsg func, queries again seenMessage func which will return again false, calls the validator and return on line 648;
3. after the first validator launched finish its job, it will write on chan sendMsg the send request which will trigger the call of publishMessage from line 392 which will mark the message m as seen;
4. if the same message m comes again, it will not be revalidated as the seenMessages is updated.

The problem was identified only recently, the commit that changed the calling of markSeen method order was 67eece25262fcbc36c93daf67da5de2daa01de49 from Jan 21, 2019. Before this change, validator func was called only once for a message.

**Comment by vyzo** [comment]
The change you mention was made to close a hole that would lead to a potential censorship/cache poisoning  attack.
The problem was that any peer that could predict the message id of another peer (an observation of a prior message is sufficient), could launch an attack where they generated invalid messages with the next message ids of the targeted peer.
If those message were marked prior to validation (which was the case before the patch), then the cache would be poisoned and valid messages from the targeted peer would be rejected.
Hence we decided to mark messages after validation.
Note that we were fully aware that this would lead to a single message potentially being validated multiple times, but decided to take that cost.

**Comment by iulianpascalau** [comment]
Ok, got it. Maybe, if signing on messages becomes mandatory, message.Signature might become the msgID and markSeen could be called in pushMsg func.

**Comment by vyzo** [comment]
That's not a bad idea.

**Comment by vyzo** [comment]
#176 fixes the issue -- it now ensures that user validators are invoked at most once for each message by marking them as seen as soon as the signature has been verified.

**Comment by iulianpascalau** [comment]
Great news! Thanks.
