### ISSUE TITLE
Unit /Regression tests for gossipsub v1.1

### ISSUE THREAD

**Issue by vyzo** [libp2p/go-libp2p-pubsub#281]
With the hardening work in #263 complete, we are ready to merge into master based on extensive testing in testground.
On the same time we lack unit tests to catch _regressions_.
This issue is here to track progress towards this goal.

**Comment by dirkmc** [comment]
Tests to add:
- [x] IWANT spam
  Peers periodically publish a list of message IDs still in their cache via gossip.  It is possible to repeatedly request the messages, causing the target to allocate CPU and bandwidth for no productive reason.
- [x] GRAFT spam
  The attacker sends GRAFTs for unknown/non-existent topics to peers in order to overload them and potentially make them send PRUNE messages to legitimate peers.
- [x] Invalid message spam
  The aim of this attack is to overload the target with Invalid Messages and cause it to slow down due to increased expenditure on `BANDWIDTH`, `CPU` and `RAM` resources. These can either be random SPAM, or messages that are pretending to be legitimate.

**Comment by vyzo** [comment]
we have more tests to write!

**Comment by vyzo** [comment]
ah, suerpseded by #287
