### ISSUE TITLE
Isn't FloodSub is a leaky abstraction?

### ISSUE THREAD

**Issue by mgoelzer** [libp2p/go-libp2p-pubsub#75]
As a developer using libp2p, I understand that libp2p provides a publish-subscribe message passing system.  I shouldn't need to know or care how it is implemented (flooding).  However, by using the word "flood" in the name of objects and imports, an implementation detail about the use of flooding is being leaked through to me.

It would be preferable to remove the word `flood` in interfaces exposed to higher level code.

Thoughts?

**Comment by vyzo** [comment]
We want to move this repo to `go-libp2p-pubsub`, once we are ready to merge gossipsub (#67).

**Comment by mgoelzer** [comment]
@vyzo #67 looks awesome.  But the interface for higher level application programmers to instantiate a pubsub object will still be `floodsub.NewPubSub()`, right?  Still leaks the flood implementation detail?

**Comment by vyzo** [comment]
We'll have a pubsub object and different constructors for the different routing algorithms.
So it will be `pubsub.NewFloodSub` for floodsub and `pubsub.NewGossipSub` for gossipbsub.

**Comment by hsanjuan** [comment]
I want to note that the repository name should probably be `go-libp2p-pubsub`, but there is already one, which is super confusing (https://github.com/libp2p/go-libp2p-pubsub). Also because it says it's the pubsub interface but contains no interface.

Then the `gx` `name` in `package.json` is `go-libp2p-floodsub` even though the repository is `go-floodsub` which is again confusing. These things (along with the renaming of the module to `pubsub`) should probably be fixed altogether, rather soon-ish, before more people start using it.

**Comment by mhchia** [comment]
Is the renaming still in the plan? I think it's a good timing to do it altogether with https://github.com/libp2p/go-libp2p-pubsub/issues/1

**Comment by Stebalien** [comment]
Yes. However, I'd rather not have to break everything *twice*.

@vyzo, how hard would it be to put gossipsub/floodsub in sub-packages? I assume we'll want to do that eventually but they currently access the internals of the pubsub router.

**Comment by vyzo** [comment]
Ugh, I really would prefer to keep them in package, at least for the time being.

**Comment by Stebalien** [comment]
https://github.com/libp2p/go-libp2p-pubsub/issues/4

**Comment by hsanjuan** [comment]
#89 related

**Comment by vyzo** [comment]
Closing this, as we have moved the package to `go-libp2p-pubsub`.
